### ISSUE TITLE
Initial comments

### ISSUE THREAD

**Issue by skurfer** [jordanekay/OpenMetaFileTagging#1]
Cool! Always good to see new plug-ins. I haven’t dug into the plug-in itself, but I’ve noticed some things about the project. If you used the new template, most of it is probably my fault. :-)
1. The path to `/tmp/QS/Configuration` is relative to your home directory. I’m not convinced there’s even a way to set that up correctly from within Xcode. I usually just close the project and fix it in a text editor.
2. The build fails because there are spaces in the path. If you go to the Build Phases and add quotes around the paths in the shell script, it should fix it. (Quote both the command and the plist.)
3. The repo includes some of your user-specific Xcode stuff. I’d steal the `.gitignore` from another plug-in or use [the example](http://projects.skurfer.com/QuicksilverPlug-inReference.mdown#getting_started) in step 12 of the documentation. You can also remove all references to those files from the repo without removing them from disk.
4. If I highlight the project, the File Inspector reports the organization as “Twitter, Inc.”. I assume this plug-in is not really from Twitter. :-)

Hopefully I’ll have time to look at the actual plug-in soon.

**Comment by jordanekay** [comment]
Wow, thanks for the quick feedback! The template was actually super useful, huge thanks for that. I've fixed 2-4, not sure what you mean about 1, what exactly should I edit it to?

**Comment by skurfer** [comment]
Just change line 122 in `project.pbxproj` to this:

```
path = /tmp/QS/Configuration;
```

I’ve gotten the template to add these files automatically, but it copies them into the project instead of referring to the version in `/tmp/QS`, so it’s still a manual process for now. I’ve also updated the template so the script will include the quotes.

**Comment by jordanekay** [comment]
Cool! Should be good now, take it for a spin when you get the chance. :)

**Comment by skurfer** [comment]
Other small things: In order for users to have the new version replace their existing one, you’d have to use the same bundle ID and set the bundle version to 29B or higher. You can release it as a new separate thing if you want, but a lot of users will probably end up with two conflicting plug-ins and not know what to do. The new bundle ID makes more sense of course, but unfortunately, once you pick one, you’re sort of married to it. :-)

Also, we’ve started adding a user-friendly version to all the plug-ins. This is also optional, but if you want to add it, set “Bundle versions string, short” to 2.0.0 (or whatever version you want to call it). This number is for display purposes only and shouldn’t affect the behavior of the application or the update system.

**Comment by jordanekay** [comment]
Done, thanks for showing me the ropes here. I admit that would be confusing! Can you confirm the plugin builds and installs? I have a few more in the pipeline so I want to make sure I have the process down. Thanks!

**Comment by skurfer** [comment]
Busy, sorry. Yeah, it builds right out of the gate and installing it replaces the old version. I’ll have to test actually using it later. :-)

**Comment by skurfer** [comment]
Another thing I noticed (that’s beyond your control) is that `bltrversion` seems to rearrange the property list pretty badly. Won’t hurt anything, but I don’t like to commit a bunch of non-change changes so I like to be aware of that stuff. You might be able to commit it like that once and hopefully Xcode won’t change it back, but I don’t know. This is always a problem with the extendedDescription too. Xcode doesn’t escape the HTML tags, but `bltrversion` does. So they fight.

You could always drop `bltrversion` from the build process. All it does is increase the build number. You’d have to do that by hand without it.

**Comment by skurfer** [comment]
If you’re willing to wait for [this](https://github.com/quicksilver/Quicksilver/pull/764) to get put into a release, you can use a bundle identifier that makes sense, while still replacing the old plug-in.

**Comment by pjrobertson** [comment]
The change Rob was discussing will be implemented in ß68 which will be released in the next few days.

I've used the plugin quite a bit and think it will be good to:
- Add this plugin to the official repo
- Rename the file tagging plugin and give it a better description

**Comment by skurfer** [comment]
Specifically, if you want to “change” the bundle ID, in `QSRequirements`:
1. Add a key named “version”. Its value should be 3926 (as a string)
2. Add a key named “obsoletes”. Its value should be an array with one string. The string should be the bundle ID of the old plug-in.

We can then make sure the old plug-in only shows up for users of older versions (or we could just remove it).

**Comment by pjrobertson** [comment]
@jordanekay - have all these changes been fixed, and is the version you have on the downloads page good to be added to the official repo?

Sorry for being slow with this.

If everything's good, then I suggest you:
- checkout Quicksilver 64 bit from https://github.com/quicksilver/Quicksilver/tree/64bit-support
- build 64 bit Quicksilver (release)
- make sure your project setting are to build 64 bit
- build the plugin as 64 bit
- send it to devs@qsapp.com and we'll put it up on the official repo.

Cheers

**Comment by jordanekay** [comment]
Cool—I will do this. Excited to finally have this in!

**Comment by skurfer** [comment]
> make sure your project setting are to build 64 bit

FYI, if the project is correctly reading from the `.xcconfig` files, this should be automatic.

**Comment by iandol** [comment]
Will be very happy to see this 64bit compatible and updated in the plugin list, a big thanks to @jordanekay for this!!!

**Comment by skurfer** [comment]
I don’t know if you saw on the dev list, but I finally posted all the [previously] undocumented steps we’ve been going through as we update plug-ins.

http://projects.skurfer.com/QuicksilverPlug-inReference.mdown#plugin_cleanup_and_modernization

**Comment by jordanekay** [comment]
Hey, sorry I’ve been so out of the loop with this. I plan to update it for 64-bit this weekend along with starting work on some new ones. :)

**Comment by jordanekay** [comment]
How are we looking now?

**Comment by skurfer** [comment]
Pretty good. Some small things:
- There are still a couple of build settings that are bold (meaning they aren’t taking the values from the xcconfig files)
- You could remove the references to `QSPlugIn_Debug.xcconfig` and `QSPlugIn_Release.xcconfig`. They won’t hurt anything, but they’ll turn red when quicksilver/Quicksilver#956 gets merged.
- The new syntax you’re using for arrays isn’t available yet in 10.7, so I can’t build it. :-) I’m sure we’ll all be on 10.8 and Xcode 4.4 by the end of the week though.

**Comment by jordanekay** [comment]
Cool. Yeah, wasn't sure about the Mountain Lion situation. I should have this done soon. Good to know about the settings; it seems like the process overall is much easier than it was six months ago. Can't wait to make a few more of these and I'm excited to get this one in!

**Comment by jordanekay** [comment]
Done.

**Comment by skurfer** [comment]
Cool. All looks good with the project. Now that I can build it, some more comments (it never ends – sorry):
- The documentation is a little sparse. :-) Looks like you’re already on the new `bltrversion`, which makes it [much easier](http://projects.skurfer.com/QuicksilverPlug-inReference.mdown#documentation_and_bltrversion) to maintain. If you just copy or symlink `README.mdown` to `Documentation.mdown` and build, that should take care of 95%. Our typical convention is to put notes for developers in README and put end-user stuff in Documentation, but you don’t have to follow that. Making the documentation available in the application is the important thing.
- The reason I looked for documentation: You can apparently set tags containing spaces, separating them by comma. The Spotlight plug-in uses space as a separator. I don’t think you should change the behavior, but it would be nice if these details were explained. Also, does it make sense to allow ‘,’ as a separator (without a space) as well? Or another option is to do it the way the Yojimbo plug-in does: Instead of just text entry, known tags from the catalog are shown in the third pane (and can be selected via the comma trick), while new tags can be added by switching to text entry mode. Slightly faster (and less error prone) if you’re planning to use the same tags over and over, which is probably the thing you’ll do more often, but can be a bit of a pain for entering new tags.
- The actions don’t have an icon. They’ll work fine without one, so that’s up to you. If you _do_ want to assign icons, I noticed that OpenMeta has an official logo https://code.google.com/p/openmeta/downloads/detail?name=OpenMetaLogos.zip That might be good to distinguish this plug-in’s stuff from that provided by the Spotlight plug-in.
- The name of the plug-in appears in the UI as “OpenMetaFile Tagging”. Should there be another space in there?
- The object source doesn’t provide an `indexIsValidFromDate:forEntry:` method, so it will get unconditionally rescanned every time Quicksilver updates its catalog. Honestly, that probably makes the most sense for this plug-in. Just something to be aware of.
- I’ve tested the actual functionality a bit and everything seems to be working. I’ll probably use this when it’s done, as I love the multiple tag navigation thing. (I did the same for Yojimbo. I’ll have to look at your implementation because mine was pretty insane.)

**Comment by jordanekay** [comment]
All great points. I'm considering adopting the Yojimbo style for the third pane since it seems much more useful and less error prone. One question: when you add a new tag in text entry mode, can you add one? Also, if you have multiple tags selected with the comma trick, and switch to text mode, what does it show?

**Comment by skurfer** [comment]
> when you add a new tag in text entry mode, can you add one?

You mean does manually entered text work as a tag? Yes, but that’s because the action that adds the tags just takes the string value of each object. As a result, it doesn’t really distinguish between existing tags and new tags.

> Also, if you have multiple tags selected with the comma trick, and switch to text mode, what does it show?

Good question. I’m not sure now if what I’m seeing differs from what I saw when I wrote the thing, but here’s a breakdown.

#### Works
- Selecting multiple tags with comma
- Entering multiple tags in text entry mode (by hitting ⎋ then , between each one)
- Entering multiple tags in text entry mode, then selecting multiple tags with comma

#### Doesn’t work
- Selecting multiple tags with comma, then entering text mode to enter one or more tags by hand. That just shows “combined objects”, which ends up being one of the tags applied.

I suppose I should run B54 to check the original behavior before I go to 10.8. :-)

**Comment by iandol** [comment]
Is it worth publishing this as it is so people can at least use the new V2.0 while the redesigned bits percolate through?

**Comment by jordanekay** [comment]
Sure.

**Comment by gerbenzaagsma** [comment]
would it be possible to offer this as a compiled plugin for testing? I'd love to try it out,
best,
Gerben

**Comment by jordanekay** [comment]
Sure. I can get a download up later today.

**Comment by pjrobertson** [comment]
If you build a 64 bit version, let us know and we'll put it straight on the
plugins system

Cheers

**Comment by jordanekay** [comment]
Cool, sounds great! I already have a 64-bit version built, I just want to do one final smoke check before uploading it.

I remember you explaining some improvements you’d like to see, and some behavioral changes to make it more consistent with the Yojimbo plugin. Should we open up a separate issue for that?

Thanks!

**Comment by pjrobertson** [comment]
Whatever's easiest for you. I can't remember now, so probably best to close
this and we can open new issues as things move along :)

**Comment by skurfer** [comment]
> I remember you explaining some improvements you’d like to see, and some behavioral changes to make it more consistent with the Yojimbo plugin. Should we open up a separate issue for that?

Yes. This issue is pretty overloaded. Shut it down! :-)

I can copy all the stuff from [this comment](#issuecomment-7208788) to a new issue if you want.

**Comment by gerbenzaagsma** [comment]
sorry to repeat but would it be possible to compile a version so we can test it? :)

**Comment by skurfer** [comment]
For those who asked, this plug-in has been released. You can install it from Quicksilver's prefs.

**Comment by iandol** [comment]
Excellent, thanks skurfer!!! :heart:
